version: '3.9'

services:
  mysql_server:
    image: mysql:8.0.39
    container_name: mysql8_server
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - mysql-network
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/config/mysql.cnf:/etc/mysql/conf.d/my.cnf

  cli:
    image: mysql:8.0.39
    container_name: mysql8_client
    networks:
      - mysql-network
    command: mysql -hmysql_server -u${MYSQL_USER} -p${MYSQL_PASSWORD}

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
    - mysql-network

networks:
  mysql-network:
    driver: bridge
